// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8VN9OihTv_cxEn8bLn8qeWrkpzI-RKfk',
    appId: '1:806164143095:web:58cc5a7319eb5d4695ecf2',
    messagingSenderId: '806164143095',
    projectId: 'book-bank-3c985',
    authDomain: 'book-bank-3c985.firebaseapp.com',
    storageBucket: 'book-bank-3c985.appspot.com',
    measurementId: 'G-4GGSW33WWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC75tdDhNoJVbHLMDzIbzbOg1eCfLuGZ6Q',
    appId: '1:806164143095:android:6e8135a8a81706a395ecf2',
    messagingSenderId: '806164143095',
    projectId: 'book-bank-3c985',
    storageBucket: 'book-bank-3c985.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgzHEcnVzejwAprASW6kp5BZDQ3cpwERI',
    appId: '1:806164143095:ios:0cee9ac54612e2f495ecf2',
    messagingSenderId: '806164143095',
    projectId: 'book-bank-3c985',
    storageBucket: 'book-bank-3c985.appspot.com',
    iosClientId: '806164143095-q7ufr9p4dl1uqdrut7mbvfv2mm932lec.apps.googleusercontent.com',
    iosBundleId: 'com.rubab.bookbank.bookBank',
  );
}
